name: palate_prestige
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.1

dependencies:
  flutter:
    sdk: flutter
  firebase_auth: ^5.3.1
  provider: ^6.1.2
  web_socket_channel: ^3.0.1
  mobile_scanner: ^5.2.3
  image_picker: ^1.1.2
  google_sign_in: ^6.2.1
  grouped_list: ^6.0.0
  google_fonts: ^6.2.1
  flutter_svg: ^2.0.10+1
  firebase_core: ^3.6.0
  cloud_firestore: ^5.4.4
  http: ^1.2.2
  buttons_tabbar: ^1.3.13
  socket_io_client: ^3.0.0
  lottie: ^3.1.3
  flutter_cashfree_pg_sdk: 2.1.7+37

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
