// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA8VnXU3i6uiXJ7rsaqamzjDOjS0WUT6Og',
    appId: '1:583188405875:web:a81f9854fcd6fb9c7fd406',
    messagingSenderId: '583188405875',
    projectId: 'palate-prestige',
    authDomain: 'palate-prestige.firebaseapp.com',
    storageBucket: 'palate-prestige.appspot.com',
    measurementId: 'G-9CG0QN6G3M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCNSA62ppPW3YjUsQoJNM0DtKS0s5Z_kAc',
    appId: '1:583188405875:android:dec33241c4346a3c7fd406',
    messagingSenderId: '583188405875',
    projectId: 'palate-prestige',
    storageBucket: 'palate-prestige.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAlEr9CRVDu1VAfWOXZ1s7QCDaFR-xvjUM',
    appId: '1:583188405875:ios:e3a1c3da4c5d583f7fd406',
    messagingSenderId: '583188405875',
    projectId: 'palate-prestige',
    storageBucket: 'palate-prestige.appspot.com',
    iosBundleId: 'com.example.palatePrestige',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAlEr9CRVDu1VAfWOXZ1s7QCDaFR-xvjUM',
    appId: '1:583188405875:ios:e3a1c3da4c5d583f7fd406',
    messagingSenderId: '583188405875',
    projectId: 'palate-prestige',
    storageBucket: 'palate-prestige.appspot.com',
    iosBundleId: 'com.example.palatePrestige',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA8VnXU3i6uiXJ7rsaqamzjDOjS0WUT6Og',
    appId: '1:583188405875:web:b7353547395171d67fd406',
    messagingSenderId: '583188405875',
    projectId: 'palate-prestige',
    authDomain: 'palate-prestige.firebaseapp.com',
    storageBucket: 'palate-prestige.appspot.com',
    measurementId: 'G-3C0FC12X57',
  );
}
